### ISSUE TITLE
Some questions about running this.

### ISSUE THREAD

**Issue by TeoMastro** [keligggg/FluidAttack-Casa-Tier2#1]
What is the command to run this dockerfile?
Do I go with this: https://appdefensealliance.dev/casa/tier-2/ast-guide/static-scan
or : https://docs.fluidattacks.com/tech/scanner/standalone/casa/
Both ways I did not manage to get a proper .csv
Also the what will be the file/folder structure for this, do I go with what 1st link suggests or as you have it here in your repo?

This is what I run right now, and it produces a result in the terminal but I am not sure it is correct:
`
docker run -v ~/Documents/scan-artifacts:/working-dir fluidattacks/cli:amd64 skims scan /working-dir
` (note that working-dir is not an existing folder in my system)

I also have my mobile app in an app folder as it is in the Android Studio. Also there is a debug apk in it's output folder (not that it matters but ok :P )

I hope I can get some help, thanks for your time though.

**Comment by keligggg** [comment]
Hi,

Here is my guide for a Google Apps Script application (not a mobile application)
https://medium.com/@kelig.lefeuvre/step-by-step-guide-how-to-scan-your-google-apps-script-project-for-casa-7b4a3dc9bc88
All Dockers commands and folder hierarchies are specified in the guide. 
The process should be pretty much the same.

You should probably add the APK configuration key to the [config.yaml](https://github.com/keligggg/FluidAttack-Casa-Tier2/blob/main/config.yaml) file.
See the FluidAttacks documentation: 
https://docs.fluidattacks.com/tech/scanner/standalone/configuration/keys/#apk

**Comment by TeoMastro** [comment]
Nice tutorial, thanks man!
